// 자동 생성 파일 — 직접 수정하지 말고 docs/data/climbing-gyms-kakao.csv 를 고친 뒤 `npm run build-gyms` 를 실행하세요.
export type GymRegion = "seoul" | "metro" | "etc";
export type Gym = { id: string; name: string; region: GymRegion; area: string; address?: string };

export const REGIONS: { value: GymRegion; label: string }[] = [
  { value: "seoul", label: "서울권" },
  { value: "metro", label: "서울 외 수도권" },
  { value: "etc", label: "수도권 외" },
];

export const GYMS: Gym[] = [
  {"id":"seoul-081dzio","name":"더클라임 강남점","region":"seoul","area":"서울 강남구","address":"서울 강남구 테헤란로8길 21"},
  {"id":"seoul-07t9hjk","name":"더클라임 양재점","region":"seoul","area":"서울 강남구","address":"서울 강남구 남부순환로 2615"},
  {"id":"seoul-0ej613g","name":"역삼클라이밍랩","region":"seoul","area":"서울 강남구","address":"서울 강남구 테헤란로30길 49"},
  {"id":"seoul-1gy8vc1","name":"콜스에듀케이션","region":"seoul","area":"서울 강남구","address":"서울 강남구 논현로76길 27"},
  {"id":"seoul-0y664gp","name":"클라이밍파크 강남점","region":"seoul","area":"서울 강남구","address":"서울 강남구 강남대로 364"},
  {"id":"seoul-1x94gcc","name":"클라이밍파크 신논현점","region":"seoul","area":"서울 강남구","address":"서울 강남구 강남대로 468"},
  {"id":"seoul-0hkcjjx","name":"클라임투게더","region":"seoul","area":"서울 강남구","address":"서울 강남구 영동대로 602"},
  {"id":"seoul-0a6hrql","name":"알레클라임","region":"seoul","area":"서울 강동구","address":"서울 강동구 천호대로177길 39"},
  {"id":"seoul-1y7eqmc","name":"온세대클라이밍","region":"seoul","area":"서울 강동구","address":"서울 강동구 양재대로 1300"},
  {"id":"seoul-1ilv56x","name":"온플릭클라이밍 천호점","region":"seoul","area":"서울 강동구","address":"서울 강동구 올림픽로 664"},
  {"id":"seoul-0rsbaxk","name":"쿠키즈클라이밍","region":"seoul","area":"서울 강동구","address":"서울 강동구 양재대로 1620"},
  {"id":"seoul-15315td","name":"맥클라이밍","region":"seoul","area":"서울 강북구","address":"서울 강북구 수유로 30"},
  {"id":"seoul-0kl9d18","name":"블랙야크 야크돔","region":"seoul","area":"서울 강북구","address":"서울 강북구 삼양로173길 52"},
  {"id":"seoul-07z2gdg","name":"더클라임 마곡점","region":"seoul","area":"서울 강서구","address":"서울 강서구 마곡동로 62"},
  {"id":"seoul-08992y4","name":"어거스트클라이밍","region":"seoul","area":"서울 강서구","address":"서울 강서구 양천로 461"},
  {"id":"seoul-0hkal10","name":"클라이밍88","region":"seoul","area":"서울 강서구","address":"서울 강서구 공항대로 376"},
  {"id":"seoul-07v4pug","name":"더클라임 사당점","region":"seoul","area":"서울 관악구","address":"서울 관악구 과천대로 939"},
  {"id":"seoul-07u44tt","name":"더클라임 신림점","region":"seoul","area":"서울 관악구","address":"서울 관악구 신원로 35"},
  {"id":"seoul-1uoxf8c","name":"스톤즈클라이밍","region":"seoul","area":"서울 관악구","address":"서울 관악구 남부순환로 1990-3"},
  {"id":"seoul-1n15g8c","name":"레드포인트클라이밍","region":"seoul","area":"서울 광진구","address":"서울 광진구 천호대로109길 9"},
  {"id":"seoul-1ti3e34","name":"버티고클라이밍짐","region":"seoul","area":"서울 광진구","address":"서울 광진구 천호대로 611"},
  {"id":"seoul-1kdczeq","name":"서울숲클라이밍 구로점","region":"seoul","area":"서울 구로구","address":"서울 구로구 디지털로 300"},
  {"id":"seoul-0aqmnzc","name":"썬클라이밍짐","region":"seoul","area":"서울 구로구","address":"서울 구로구 구로동로 215-1"},
  {"id":"seoul-0ts1820","name":"위클리클라이밍","region":"seoul","area":"서울 구로구","address":"서울 구로구 경인로47길 68"},
  {"id":"seoul-0icnr5k","name":"피커스클라이밍 구로","region":"seoul","area":"서울 구로구","address":"서울 구로구 구로중앙로 152"},
  {"id":"seoul-039grf0","name":"드림캐처클라이밍짐","region":"seoul","area":"서울 노원구","address":"서울 노원구 상계로5길 32"},
  {"id":"seoul-0npleoc","name":"볼더클라이밍짐","region":"seoul","area":"서울 노원구","address":"서울 노원구 동일로241길 53"},
  {"id":"seoul-1l5dmgt","name":"비숍클라이밍","region":"seoul","area":"서울 노원구","address":"서울 노원구 동일로 1393"},
  {"id":"seoul-1yhix1w","name":"오름클라이밍","region":"seoul","area":"서울 노원구","address":"서울 노원구 상계로12길 32"},
  {"id":"seoul-16du1n8","name":"산타클라이밍짐","region":"seoul","area":"서울 동대문구","address":"서울 동대문구 난계로30길 23"},
  {"id":"seoul-1d2sh4s","name":"웨어하우스 볼더링","region":"seoul","area":"서울 동대문구","address":"서울 동대문구 경동시장로23길 5"},
  {"id":"seoul-07v12wx","name":"더클라임 이수점","region":"seoul","area":"서울 동작구","address":"서울 동작구 동작대로 59"},
  {"id":"seoul-19jlj2k","name":"볼더생활","region":"seoul","area":"서울 동작구","address":"서울 동작구 동작대로29길 69"},
  {"id":"seoul-07srxf9","name":"더클라임 연남점","region":"seoul","area":"서울 마포구","address":"서울 마포구 양화로 186"},
  {"id":"seoul-09bkyow","name":"코알라클라이밍짐","region":"seoul","area":"서울 마포구","address":"서울 마포구 월드컵북로 396"},
  {"id":"seoul-1nw47ix","name":"홍대클라이밍","region":"seoul","area":"서울 마포구","address":"서울 마포구 동교로23길 105"},
  {"id":"seoul-0qkz6bc","name":"신촌담장","region":"seoul","area":"서울 서대문구","address":"서울 서대문구 신촌역로 10"},
  {"id":"seoul-1sqzmx1","name":"피커스 신촌점","region":"seoul","area":"서울 서대문구","address":"서울 서대문구 신촌로 129"},
  {"id":"seoul-07x8cr9","name":"더클라임 논현점","region":"seoul","area":"서울 서초구","address":"서울 서초구 강남대로 519"},
  {"id":"seoul-1d6wb2g","name":"손상원클라이밍짐 강남점","region":"seoul","area":"서울 서초구","address":"서울 서초구 강남대로 331"},
  {"id":"seoul-0zrx8u4","name":"그루트클라이밍","region":"seoul","area":"서울 성동구","address":"서울 성동구 성수일로 19"},
  {"id":"seoul-07uoio4","name":"더클라임 성수점","region":"seoul","area":"서울 성동구","address":"서울 성동구 아차산로17길 49"},
  {"id":"seoul-19r7fed","name":"훅클라이밍 왕십리점","region":"seoul","area":"서울 성동구","address":"서울 성동구 고산자로6길 40"},
  {"id":"seoul-0fv6lzn","name":"닷클라이밍짐","region":"seoul","area":"서울 송파구","address":"서울 송파구 법원로8길 9"},
  {"id":"seoul-00b1les","name":"루트클라이밍","region":"seoul","area":"서울 송파구","address":"서울 송파구 양재대로71길 5-14"},
  {"id":"seoul-11kqw3l","name":"브릭스클라이밍짐","region":"seoul","area":"서울 송파구","address":"서울 송파구 중대로 130"},
  {"id":"seoul-1jzxlx2","name":"서울숲클라이밍 잠실점","region":"seoul","area":"서울 송파구","address":"서울 송파구 백제고분로7길 49"},
  {"id":"seoul-0hkgjm1","name":"클라임투더문","region":"seoul","area":"서울 송파구","address":"서울 송파구 백제고분로 224"},
  {"id":"seoul-1w12jz1","name":"서울볼더스 목동","region":"seoul","area":"서울 양천구","address":"서울 양천구 신목로 53"},
  {"id":"seoul-07y2c7h","name":"더클라임 문래점","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 당산로 63"},
  {"id":"seoul-1w1hcr1","name":"서울볼더스 선유","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 양평로28마길 7"},
  {"id":"seoul-00r4nny","name":"서울숲클라이밍 영등포점","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 문래로 164"},
  {"id":"seoul-1oy83v4","name":"서종국클라이밍짐","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 선유로53길 6"},
  {"id":"seoul-13tbpj5","name":"알레클라임 영등포점","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 영등포로33길 14"},
  {"id":"seoul-0yyh96p","name":"클라임러버","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 당산로49길 12"},
  {"id":"seoul-0yyuzz4","name":"클라임웍스","region":"seoul","area":"서울 영등포구","address":"서울 영등포구 버드나루로 85"},
  {"id":"seoul-1ew2bys","name":"오프더월클라이밍","region":"seoul","area":"서울 용산구","address":"서울 용산구 이태원로 190"},
  {"id":"seoul-1wf8god","name":"행클라임 클라이밍짐 구파발점","region":"seoul","area":"서울 은평구","address":"서울 은평구 통일로 1020"},
  {"id":"seoul-1jwqzjf","name":"서울숲클라이밍 종로점","region":"seoul","area":"서울 종로구","address":"서울 종로구 수표로 96"},
  {"id":"seoul-0isfkzs","name":"알레클라이밍 혜화점","region":"seoul","area":"서울 종로구","address":"서울 종로구 창경궁로34길 18-5"},
  {"id":"seoul-0yb10l9","name":"클라이밍파크 종로점","region":"seoul","area":"서울 종로구","address":"서울 종로구 종로 199-1"},
  {"id":"seoul-1su1igg","name":"피커스 종로점","region":"seoul","area":"서울 종로구","address":"서울 종로구 돈화문로5가길 1"},
  {"id":"seoul-1m3synh","name":"손상원 클라이밍짐 을지로점","region":"seoul","area":"서울 중구","address":"서울 중구 남대문로 125"},
  {"id":"seoul-1vnbvnh","name":"을지로 담장 클라이밍","region":"seoul","area":"서울 중구","address":"서울 중구 마른내로 63-3"},
  {"id":"seoul-0bc4y9c","name":"플래시볼더스 클라이밍","region":"seoul","area":"서울 중구","address":"서울 중구 서애로5길 21"},
  {"id":"seoul-1vdble0","name":"마스터클라이밍","region":"seoul","area":"서울 중랑구","address":"서울 중랑구 용마산로115길 65"},
  {"id":"seoul-0dcblac","name":"크래커클라이밍","region":"seoul","area":"서울 중랑구","address":"서울 중랑구 면목로92길 37-4"},
  {"id":"metro-1wp0xis","name":"강화클라이밍","region":"metro","area":"인천 강화군","address":"인천 강화군 불은면 중앙로 546-34"},
  {"id":"metro-0e4ut58","name":"클라임스퀘어 ICN본점","region":"metro","area":"인천 검단구","address":"인천 검단구 완정로 70"},
  {"id":"metro-1hgahqw","name":"기필코홀드","region":"metro","area":"인천 남동구","address":"인천 남동구 호구포로 189"},
  {"id":"metro-1bra24l","name":"볼리클라이밍","region":"metro","area":"인천 남동구","address":"인천 남동구 서창남순환로216번길 30"},
  {"id":"metro-1hse3ip","name":"허브클라이밍","region":"metro","area":"인천 남동구","address":"인천 남동구 논고개로123번길 17"},
  {"id":"metro-0dup1wt","name":"서인천클라이밍","region":"metro","area":"인천 서해구","address":"인천 서해구 가정로 374"},
  {"id":"metro-0b51n29","name":"클라임스퀘어 청라점","region":"metro","area":"인천 서해구","address":"인천 서해구 청라라임로 71"},
  {"id":"metro-1j1exwx","name":"디스커버리씨에스 송도지점","region":"metro","area":"인천 연수구","address":"인천 연수구 송도과학로16번길 33-4"},
  {"id":"metro-0ig4ukd","name":"비블럭클라이밍 송도점","region":"metro","area":"인천 연수구","address":"인천 연수구 송도과학로16번길 13-39"},
  {"id":"metro-1jkatrt","name":"클라이밍줌","region":"metro","area":"인천 연수구","address":"인천 연수구 청능대로 75"},
  {"id":"metro-1dtf61w","name":"비블럭클라이밍 영종하늘도시점","region":"metro","area":"인천 영종구","address":"인천 영종구 하늘중앙로195번길 18"},
  {"id":"metro-1tcj2yo","name":"더클라임 일산점","region":"metro","area":"경기 고양시","address":"경기 고양시 일산동구 중앙로 1160"},
  {"id":"metro-13fdxsx","name":"일산SK클라이밍","region":"metro","area":"경기 고양시","address":"경기 고양시 일산동구 일산로286번길 13-5"},
  {"id":"metro-1o31ie8","name":"코알라클라이밍 킨텍스점","region":"metro","area":"경기 고양시","address":"경기 고양시 일산서구 중앙로 1560-34"},
  {"id":"metro-1jeyr2k","name":"클라이밍 업더월 일산점","region":"metro","area":"경기 고양시","address":"경기 고양시 일산서구 경의로 805"},
  {"id":"metro-1m5hx8w","name":"클라이밍 하이프렉스","region":"metro","area":"경기 고양시","address":"경기 고양시 일산서구 덕이로 20"},
  {"id":"metro-1mkazip","name":"페퍼 클라이밍","region":"metro","area":"경기 고양시","address":"경기 고양시 덕양구 권율대로 656"},
  {"id":"metro-0fslyr9","name":"하이포인트 클라이밍","region":"metro","area":"경기 고양시","address":"경기 고양시 덕양구 세솔로1길 19-2"},
  {"id":"metro-0o7pdt5","name":"마운틴스타 클라이밍짐","region":"metro","area":"경기 구리시","address":"경기 구리시 체육관로 82"},
  {"id":"metro-1yow8ww","name":"락클라이밍산본","region":"metro","area":"경기 군포시","address":"경기 군포시 광정로 60"},
  {"id":"metro-1j4uhx1","name":"스파이시 클라이밍","region":"metro","area":"경기 군포시","address":"경기 군포시 엘에스로 153-8"},
  {"id":"metro-1vtun55","name":"잼클라이밍","region":"metro","area":"경기 김포시","address":"경기 김포시 김포한강2로 76"},
  {"id":"metro-1ri47os","name":"키클 클라이밍 풍무점","region":"metro","area":"경기 김포시","address":"경기 김포시 풍무로146번길 14"},
  {"id":"metro-1ojk2kd","name":"테키클라이밍","region":"metro","area":"경기 김포시","address":"경기 김포시 고촌읍 이화남로 141"},
  {"id":"metro-0d57jfs","name":"픽클라이밍","region":"metro","area":"경기 김포시","address":"경기 김포시 김포한강4로 507"},
  {"id":"metro-0m7wqyl","name":"다이노클라이밍","region":"metro","area":"경기 남양주시","address":"경기 남양주시 다산중앙로146번길 12-14"},
  {"id":"metro-045fekl","name":"무브온클라이밍","region":"metro","area":"경기 남양주시","address":"경기 남양주시 진접읍 진건오남로 982-28"},
  {"id":"metro-0d80z89","name":"엠투클라이밍","region":"metro","area":"경기 남양주시","address":"경기 남양주시 다산순환로 356"},
  {"id":"metro-042jw8p","name":"퍼즐클라이밍","region":"metro","area":"경기 남양주시","address":"경기 남양주시 다산중앙로19번길 15"},
  {"id":"metro-09vts0t","name":"월드클라이밍","region":"metro","area":"경기 부천시","address":"경기 부천시 원미구 상동로 90"},
  {"id":"metro-1w4fgkt","name":"캐치스톤클라이밍짐","region":"metro","area":"경기 부천시","address":"경기 부천시 원미구 부천로 11"},
  {"id":"metro-00tga9p","name":"그립픽클라이밍짐","region":"metro","area":"경기 성남시","address":"경기 성남시 수정구 위례광장로 104"},
  {"id":"metro-0y9j860","name":"더볼더","region":"metro","area":"경기 성남시","address":"경기 성남시 분당구 미금일로90번길 36-5"},
  {"id":"metro-1lx7q80","name":"락페이스클라이밍","region":"metro","area":"경기 성남시","address":"경기 성남시 중원구 산성대로 340-1"},
  {"id":"metro-1mdi635","name":"비클라이밍","region":"metro","area":"경기 성남시","address":"경기 성남시 분당구 백현로144번길 29-1"},
  {"id":"metro-02cithw","name":"손상원클라이밍짐 판교점","region":"metro","area":"경기 성남시","address":"경기 성남시 분당구 대왕판교로 670"},
  {"id":"metro-0w0w79c","name":"클라임 어스 모란점","region":"metro","area":"경기 성남시","address":"경기 성남시 중원구 성남대로 1126"},
  {"id":"metro-0mvfr29","name":"그래비티클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 영통구 효원로 400"},
  {"id":"metro-0qdm5c9","name":"수원라온클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 권선구 정조로 538"},
  {"id":"metro-1cjkej0","name":"수원크럭스존클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 팔달구 인계로 63"},
  {"id":"metro-1jypocl","name":"슈퍼비 클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 영통구 청명남로 40"},
  {"id":"metro-00ckv1h","name":"에픽클라임","region":"metro","area":"경기 수원시","address":"경기 수원시 영통구 영통로 103"},
  {"id":"metro-1hxp6ax","name":"킨디클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 권선구 세화로 124"},
  {"id":"metro-01w4go5","name":"킹콩클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 팔달구 경수대로 572"},
  {"id":"metro-02vebrg","name":"피크닉클라이밍","region":"metro","area":"경기 수원시","address":"경기 수원시 팔달구 효원로 278"},
  {"id":"metro-1s8povg","name":"볼더가든","region":"metro","area":"경기 시흥시","address":"경기 시흥시 은계호수로 49"},
  {"id":"metro-1041wz1","name":"캐치클라이밍짐","region":"metro","area":"경기 시흥시","address":"경기 시흥시 장현장곡로 2"},
  {"id":"metro-0km5h07","name":"클라임잇 클라이밍 목감점","region":"metro","area":"경기 시흥시","address":"경기 시흥시 배미골길 24"},
  {"id":"metro-194gsel","name":"안산선부클라이밍","region":"metro","area":"경기 안산시","address":"경기 안산시 단원구 선부광장1로 124"},
  {"id":"metro-14viq8l","name":"클라이밍 트리클","region":"metro","area":"경기 안산시","address":"경기 안산시 단원구 화랑로 402"},
  {"id":"metro-1socxb0","name":"클럽클라이밍","region":"metro","area":"경기 안산시","address":"경기 안산시 단원구 고잔로 76"},
  {"id":"metro-0j88blx","name":"원더월클라이밍","region":"metro","area":"경기 안성시","address":"경기 안성시 공도읍 진건중길 121"},
  {"id":"metro-1qc3g09","name":"클라이밍더하기","region":"metro","area":"경기 안성시","address":"경기 안성시 보개원삼로 147"},
  {"id":"metro-0bwve2i","name":"더렛지 클라이밍","region":"metro","area":"경기 안양시","address":"경기 안양시 동안구 시민대로 115"},
  {"id":"metro-13mftt0","name":"에어즈락 클라이밍 범계점","region":"metro","area":"경기 안양시","address":"경기 안양시 동안구 시민대로 161"},
  {"id":"metro-1pzkywo","name":"펀클라임짐","region":"metro","area":"경기 안양시","address":"경기 안양시 동안구 시민대로327번길 6"},
  {"id":"metro-1wvj7al","name":"더바이브클라이밍","region":"metro","area":"경기 양주시","address":"경기 양주시 옥정동로7가길 36"},
  {"id":"metro-1jx66e4","name":"경기레포츠클라이밍","region":"metro","area":"경기 용인시","address":"경기 용인시 기흥구 흥덕1로 13"},
  {"id":"metro-1cbhmo6","name":"더그릿클라이밍","region":"metro","area":"경기 용인시","address":"경기 용인시 기흥구 동백중앙로 225-6"},
  {"id":"metro-1fv0sow","name":"볼더메이트 클라이밍 기흥점","region":"metro","area":"경기 용인시","address":"경기 용인시 기흥구 기흥로 58"},
  {"id":"metro-1g0ebsd","name":"볼더메이트 클라이밍 수지점","region":"metro","area":"경기 용인시","address":"경기 용인시 수지구 문정로 13"},
  {"id":"metro-0xpzsbo","name":"오르자","region":"metro","area":"경기 용인시","address":"경기 용인시 기흥구 기곡로 54"},
  {"id":"metro-0n1cqwr","name":"에잇픽스클라이밍","region":"metro","area":"경기 의왕시","address":"경기 의왕시 계원대학로 22"},
  {"id":"metro-15adj0x","name":"샤모니클라이밍","region":"metro","area":"경기 의정부시","address":"경기 의정부시 경의로 48"},
  {"id":"metro-0wgzsmd","name":"클라임바운스 창전점","region":"metro","area":"경기 이천시","address":"경기 이천시 이섭대천로 1229"},
  {"id":"metro-1f6urp4","name":"클라임원","region":"metro","area":"경기 이천시","address":"경기 이천시 이섭대천로 1458"},
  {"id":"metro-064rao1","name":"타잔클라이밍","region":"metro","area":"경기 이천시","address":"경기 이천시 마장면 중앙로10번길 30"},
  {"id":"metro-00818np","name":"트윈클라이밍짐","region":"metro","area":"경기 평택시","address":"경기 평택시 평택3로 30"},
  {"id":"metro-07u1ptt","name":"프리월클라이밍짐 평택지제점","region":"metro","area":"경기 평택시","address":"경기 평택시 세교8길 30"},
  {"id":"metro-0pv5j5p","name":"홍종열클라이밍짐 평택점","region":"metro","area":"경기 평택시","address":"경기 평택시 비전2로 216"},
  {"id":"metro-0kajlc1","name":"힐앤토클라이밍","region":"metro","area":"경기 평택시","address":"경기 평택시 팽성읍 송화택지로 139"},
  {"id":"metro-025jsbg","name":"클라임어스 미사점","region":"metro","area":"경기 하남시","address":"경기 하남시 미사강변동로 81"},
  {"id":"metro-1rns89c","name":"문클라임","region":"metro","area":"경기 화성시","address":"경기 화성시 동탄구 동탄원천로 338"},
  {"id":"metro-09e4ru9","name":"볼더박스 클라임","region":"metro","area":"경기 화성시","address":"경기 화성시 병점구 경기대로 1038"},
  {"id":"metro-1m49qvp","name":"클라임어클락","region":"metro","area":"경기 화성시","address":"경기 화성시 동탄구 동탄기흥로257번가길 33"},
  {"id":"metro-1jx1ztc","name":"홀드앤락클라이밍","region":"metro","area":"경기 화성시","address":"경기 화성시 만세구 남양읍 남양로 695"},
  {"id":"metro-109w321","name":"화성클라이밍클럽","region":"metro","area":"경기 화성시","address":"경기 화성시 효행구 효행로 287"},
  {"id":"metro-1jjs7qy","name":"CL클라이밍","region":"metro","area":"경기 화성시","address":"경기 화성시 동탄구 동탄대로 446"},
  {"id":"etc-1xbvvsq","name":"웨이브락 부산대점","region":"etc","area":"부산 금정구","address":"부산 금정구 장전온천천로 51"},
  {"id":"etc-1djo0me","name":"리버스락","region":"etc","area":"부산 기장군","address":"부산 기장군 정관읍 정관7로 33-8"},
  {"id":"etc-037p1e2","name":"하이클라이밍","region":"etc","area":"부산 기장군","address":"부산 기장군 정관읍 곰내길 654-168"},
  {"id":"etc-1yvcr9j","name":"락오디세이 동래점","region":"etc","area":"부산 동래구","address":"부산 동래구 안남로31번길 6"},
  {"id":"etc-14iqcre","name":"아트클라이밍","region":"etc","area":"부산 동래구","address":"부산 동래구 아시아드대로219번길 23"},
  {"id":"etc-0m02zxz","name":"돌멩이클라이밍","region":"etc","area":"부산 부산진구","address":"부산 부산진구 전포대로 162"},
  {"id":"etc-1uhy336","name":"웨이브락 서면점","region":"etc","area":"부산 부산진구","address":"부산 부산진구 서전로9번길 20"},
  {"id":"etc-12npyrv","name":"락클라이밍짐","region":"etc","area":"부산 북구","address":"부산 북구 의성로 79"},
  {"id":"etc-1leciiz","name":"SO클라이밍짐 화명점","region":"etc","area":"부산 북구","address":"부산 북구 금곡대로303번길 61"},
  {"id":"etc-10cfqca","name":"클럽스파이더클라이밍 사상점","region":"etc","area":"부산 사상구","address":"부산 사상구 학감대로252번길 59"},
  {"id":"etc-1r8jak7","name":"포고클라임","region":"etc","area":"부산 사상구","address":"부산 사상구 사상로 415"},
  {"id":"etc-0y9pqgi","name":"오터클라이밍","region":"etc","area":"부산 사하구","address":"부산 사하구 낙동대로 498"},
  {"id":"etc-0pi2y7r","name":"짱클라이밍","region":"etc","area":"부산 사하구","address":"부산 사하구 다대로429번길 5"},
  {"id":"etc-1ukvbwe","name":"웨이브락 남천점","region":"etc","area":"부산 수영구","address":"부산 수영구 황령대로473번길 15"},
  {"id":"etc-1pu7bk6","name":"핸즈클라이밍짐","region":"etc","area":"대구 남구","address":"대구 남구 이천로 34"},
  {"id":"etc-08qsvqu","name":"노루클라이밍","region":"etc","area":"대구 달서구","address":"대구 달서구 진천로23길 58"},
  {"id":"etc-15ll21v","name":"손세동클라이밍 대구두류점","region":"etc","area":"대구 달서구","address":"대구 달서구 달구벌대로 1770"},
  {"id":"etc-0td02ei","name":"초크업 더 볼더","region":"etc","area":"대구 달서구","address":"대구 달서구 이곡공원로 24"},
  {"id":"etc-0atcu1e","name":"초크업클라이밍 월성점","region":"etc","area":"대구 달서구","address":"대구 달서구 상원로 184-8"},
  {"id":"etc-1nnerre","name":"클라이밍하이","region":"etc","area":"대구 달서구","address":"대구 달서구 도원로 12"},
  {"id":"etc-1n3jpli","name":"킹콩클라이밍","region":"etc","area":"대구 달서구","address":"대구 달서구 호산동로 187"},
  {"id":"etc-008rm2m","name":"몬스터클라이밍","region":"etc","area":"대구 달성군","address":"대구 달성군 유가읍 테크노상업로 98"},
  {"id":"etc-0vvzqkt","name":"다이노캣 클라이밍","region":"etc","area":"대구 동구","address":"대구 동구 안심로 52"},
  {"id":"etc-0wtzrjr","name":"벽클라이밍스쿨","region":"etc","area":"대구 북구","address":"대구 북구 중앙대로 617"},
  {"id":"etc-0afg5t2","name":"손세동클라이밍 칠곡점","region":"etc","area":"대구 북구","address":"대구 북구 동천로23길 8"},
  {"id":"etc-0wqu7or","name":"에브리클라임","region":"etc","area":"대구 북구","address":"대구 북구 침산로22길 5"},
  {"id":"etc-0agvxeb","name":"챌린져클라이밍 칠곡점","region":"etc","area":"대구 북구","address":"대구 북구 학정로 419"},
  {"id":"etc-0b1r4h6","name":"초크업클라이밍 경대점","region":"etc","area":"대구 북구","address":"대구 북구 동북로 288"},
  {"id":"etc-0aulhn3","name":"초크업클라이밍 침산점","region":"etc","area":"대구 북구","address":"대구 북구 침산남로 92"},
  {"id":"etc-1xwed5m","name":"M클라이밍 칠곡점","region":"etc","area":"대구 북구","address":"대구 북구 구리로 201-1"},
  {"id":"etc-11fy1bu","name":"볼더라운지 플립 대구점","region":"etc","area":"대구 서구","address":"대구 서구 달성공원로 9-2"},
  {"id":"etc-0d1wm27","name":"뉴비클라이밍 수성점","region":"etc","area":"대구 수성구","address":"대구 수성구 수성로 146"},
  {"id":"etc-01yueki","name":"동성로클라이밍짐","region":"etc","area":"대구 중구","address":"대구 중구 동성로 10-1"},
  {"id":"etc-1do5r8w","name":"그랩잇 클라이밍","region":"etc","area":"광주 광산구","address":"전남광주통합특별시 광산구 임방울대로 507"},
  {"id":"etc-0sfuloi","name":"레드원클라이밍첨단","region":"etc","area":"광주 광산구","address":"전남광주통합특별시 광산구 첨단강변로87번길 20"},
  {"id":"etc-10pmceh","name":"빛고을클라이밍 첨단점","region":"etc","area":"광주 광산구","address":"전남광주통합특별시 광산구 임방울대로 785"},
  {"id":"etc-032xkz2","name":"온클라이밍","region":"etc","area":"광주 광산구","address":"전남광주통합특별시 광산구 장신로 72"},
  {"id":"etc-0de3phg","name":"G1클라이밍 송정","region":"etc","area":"광주 광산구","address":"전남광주통합특별시 광산구 광산로 87"},
  {"id":"etc-0uf60zm","name":"레드원클라이밍","region":"etc","area":"광주 남구","address":"전남광주통합특별시 남구 봉선2로 81"},
  {"id":"etc-0hzjcbu","name":"클라이븐클라이밍 컴퍼니","region":"etc","area":"광주 동구","address":"전남광주통합특별시 동구 충장로안길 40-2"},
  {"id":"etc-0apgnsj","name":"핸드워크클라이밍 양산점","region":"etc","area":"광주 북구","address":"전남광주통합특별시 북구 임방울대로 1068"},
  {"id":"etc-0ul08du","name":"핸드워크클라이밍짐","region":"etc","area":"광주 북구","address":"전남광주통합특별시 북구 서방로 10"},
  {"id":"etc-0rmizhv","name":"인케이브 클라이밍짐 상무점","region":"etc","area":"광주 서구","address":"전남광주통합특별시 서구 상무중앙로 46"},
  {"id":"etc-1nno6qb","name":"클라임라운지","region":"etc","area":"광주 서구","address":"전남광주통합특별시 서구 금화로383번길 10"},
  {"id":"etc-1p735b2","name":"어웨이크클라이밍 타임월드점","region":"etc","area":"대전 서구","address":"대전 서구 둔산로 18"},
  {"id":"etc-0imr04y","name":"대전하나클라이밍짐","region":"etc","area":"대전 유성구","address":"대전 유성구 월드컵대로 32"},
  {"id":"etc-1m1vm3r","name":"클라이밍짐 리드 유성점","region":"etc","area":"대전 유성구","address":"대전 유성구 계룡로 129"},
  {"id":"etc-0k1ein6","name":"라온클라이밍짐","region":"etc","area":"울산 남구","address":"울산 남구 삼산로 48"},
  {"id":"etc-0qrdmwj","name":"업클라이밍짐","region":"etc","area":"울산 남구","address":"울산 남구 대학로 130"},
  {"id":"etc-13wjveu","name":"월담클라이밍","region":"etc","area":"울산 남구","address":"울산 남구 삼산중로48번길 9"},
  {"id":"etc-1p8h0jf","name":"몽클라이밍","region":"etc","area":"울산 북구","address":"울산 북구 당수골2길 43"},
  {"id":"etc-1d90rvb","name":"영남알프스 국제클라이밍장","region":"etc","area":"울산 울주군","address":"울산 울주군 상북면 알프스온천5길 122"},
  {"id":"etc-1tul767","name":"9클라이밍짐","region":"etc","area":"울산 중구","address":"울산 중구 당산길 26"},
  {"id":"etc-1w5b81u","name":"별클라이밍","region":"etc","area":"세종 아름동","address":"세종특별자치시 보듬3로 158"},
  {"id":"etc-1nmxeje","name":"클라이밍강릉","region":"etc","area":"강원 강릉시","address":"강원특별자치도 강릉시 정원로 42"},
  {"id":"etc-09lhepg","name":"아임낫볼더","region":"etc","area":"강원 속초시","address":"강원특별자치도 속초시 엑스포로 75"},
  {"id":"etc-11brjci","name":"에이짐클라이밍","region":"etc","area":"강원 속초시","address":"강원특별자치도 속초시 만리공원길 8"},
  {"id":"etc-1pejwfh","name":"천당릿지","region":"etc","area":"강원 속초시","address":"강원특별자치도 속초시 설악동 산 41"},
  {"id":"etc-0kw8bz0","name":"고고클라이밍 2호점","region":"etc","area":"강원 원주시","address":"강원특별자치도 원주시 판부면 서곡널다리길 8"},
  {"id":"etc-0r94yt6","name":"더쎈클라이밍","region":"etc","area":"강원 원주시","address":"강원특별자치도 원주시 단구로 194"},
  {"id":"etc-0oigpri","name":"차클라이밍","region":"etc","area":"강원 원주시","address":"강원특별자치도 원주시 무상길 11-1"},
  {"id":"etc-1eoz8oq","name":"클라이밍아미고","region":"etc","area":"강원 원주시","address":"강원특별자치도 원주시 서원대로 392"},
  {"id":"etc-1nnheyy","name":"클라이밍원주","region":"etc","area":"강원 원주시","address":"강원특별자치도 원주시 원일로 19"},
  {"id":"etc-16nijsj","name":"클라임투게더 원주점","region":"etc","area":"강원 원주시","address":"강원특별자치도 원주시 문막읍 동화골길 25"},
  {"id":"etc-1lpzoyy","name":"남춘천클라이밍","region":"etc","area":"강원 춘천시","address":"강원특별자치도 춘천시 춘천순환로 29"},
  {"id":"etc-090hfde","name":"속리산클라이밍장","region":"etc","area":"충북 보은군","address":"충북 보은군 속리산면 법주사로 58-2"},
  {"id":"etc-0fn80m0","name":"톺아클라이밍","region":"etc","area":"충북 제천시","address":"충북 제천시 의림대로 71"},
  {"id":"etc-1up9biz","name":"오르락클라이밍짐","region":"etc","area":"충북 충주시","address":"충북 충주시 호암수청1로 55"},
  {"id":"etc-0qzf5ke","name":"충주락클라이밍","region":"etc","area":"충북 충주시","address":"충북 충주시 용정8길 6"},
  {"id":"etc-15ykuvh","name":"서산시 클라이밍장 (2026년 예정)","region":"etc","area":"충남 서산시","address":"충남 서산시 안견로 638"},
  {"id":"etc-166k4lm","name":"서산클라이밍","region":"etc","area":"충남 서산시","address":"충남 서산시 율지3로 1"},
  {"id":"etc-1bw0iit","name":"엣지워크클라이밍","region":"etc","area":"충남 서산시","address":"충남 서산시 서해로 3443"},
  {"id":"etc-0erl11u","name":"와클라이밍 아산","region":"etc","area":"충남 아산시","address":"충남 아산시 신정호길 33-21"},
  {"id":"etc-01hgah2","name":"와클라이밍","region":"etc","area":"충남 천안시","address":"충남 천안시 동남구 목천읍 성남로 39-1"},
  {"id":"etc-1udrxy2","name":"클라임맥스","region":"etc","area":"충남 천안시","address":"충남 천안시 동남구 신촌로 24"},
  {"id":"etc-17xtx6z","name":"홍종열클라이밍짐 천안두정점","region":"etc","area":"충남 천안시","address":"충남 천안시 서북구 성정두정로 100"},
  {"id":"etc-0yuneh3","name":"온더락클라이밍","region":"etc","area":"전북 군산시","address":"전북특별자치도 군산시 백릉로 33"},
  {"id":"etc-1j0qfua","name":"홀드온클라이밍","region":"etc","area":"전북 군산시","address":"전북특별자치도 군산시 축동2길 39-4"},
  {"id":"etc-1ul2hdz","name":"클라임팜","region":"etc","area":"전북 익산시","address":"전북특별자치도 익산시 고봉로32길 34"},
  {"id":"etc-0adwnvu","name":"어센트클라이밍 만성혁신","region":"etc","area":"전북 전주시","address":"전북특별자치도 전주시 덕진구 만성중앙로 76"},
  {"id":"etc-1yuoeer","name":"어센트클라이밍 전북대","region":"etc","area":"전북 전주시","address":"전북특별자치도 전주시 덕진구 권삼득로 333"},
  {"id":"etc-1nxz5b3","name":"전주바위오름","region":"etc","area":"전북 전주시","address":"전북특별자치도 전주시 완산구 중산중앙로 8"},
  {"id":"etc-17m7wdj","name":"전주BK클라이밍짐","region":"etc","area":"전북 전주시","address":"전북특별자치도 전주시 완산구 효동3길 7"},
  {"id":"etc-10w7egv","name":"하드락클라이밍","region":"etc","area":"전북 전주시","address":"전북특별자치도 전주시 완산구 바우배기1길 11"},
  {"id":"etc-0dxb8t2","name":"리드클라이밍","region":"etc","area":"전남 목포시","address":"전남광주통합특별시 목포시 백년대로 324"},
  {"id":"etc-0htocoq","name":"목포탑매드클라임동호회","region":"etc","area":"전남 목포시","address":"전남광주통합특별시 목포시 산정로 86"},
  {"id":"etc-1fjzyf7","name":"카르페클라임","region":"etc","area":"전남 무안군","address":"전남광주통합특별시 무안군 삼향읍 대죽서로 41"},
  {"id":"etc-1qohwp7","name":"원클라임","region":"etc","area":"전남 순천시","address":"전남광주통합특별시 순천시 해룡면 낙선길 2"},
  {"id":"etc-1o4v3lb","name":"스파이더짐","region":"etc","area":"전남 여수시","address":"전남광주통합특별시 여수시 문수로 50"},
  {"id":"etc-16y15fe","name":"경산국제클라이밍파크","region":"etc","area":"경북 경산시","address":"경북 경산시 남산면 인흥리 250"},
  {"id":"etc-0e5a1di","name":"올라클라이밍","region":"etc","area":"경북 경산시","address":"경북 경산시 하양읍 하양로 56"},
  {"id":"etc-1p7wm4b","name":"플로우클라임","region":"etc","area":"경북 경주시","address":"경북 경주시 양정로328번길 11"},
  {"id":"etc-1ls5ne2","name":"노보클라이밍","region":"etc","area":"경북 구미시","address":"경북 구미시 인동북길 121"},
  {"id":"etc-1rpynmu","name":"킹스클라임","region":"etc","area":"경북 구미시","address":"경북 구미시 옥계북로 34"},
  {"id":"etc-01frdvn","name":"포시즌클라이밍 산동점","region":"etc","area":"경북 구미시","address":"경북 구미시 산동읍 신당1로 24"},
  {"id":"etc-1v42lgy","name":"상주클라이밍클럽","region":"etc","area":"경북 상주시","address":"경북 상주시 인봉2길 6"},
  {"id":"etc-1m366a2","name":"의성클라이밍장","region":"etc","area":"경북 의성군","address":"경북 의성군 의성읍 중리리 935-4"},
  {"id":"etc-1hrej0i","name":"아띠클라이밍","region":"etc","area":"경북 포항시","address":"경북 포항시 북구 우창동로 70"},
  {"id":"etc-1whx0z3","name":"포항스파이더클라이밍","region":"etc","area":"경북 포항시","address":"경북 포항시 남구 오천읍 남원로 28"},
  {"id":"etc-0mhggqa","name":"트리클라이밍","region":"etc","area":"경남 거제시","address":"경남 거제시 성산로 42"},
  {"id":"etc-1qbtz47","name":"오름놀터","region":"etc","area":"경남 고성군","address":"경남 고성군 고성읍 성내로 61"},
  {"id":"etc-04omccy","name":"두클라이밍 김해점","region":"etc","area":"경남 김해시","address":"경남 김해시 내외로77번길 12"},
  {"id":"etc-02prmsu","name":"위드클라이밍짐","region":"etc","area":"경남 김해시","address":"경남 김해시 인제로 246"},
  {"id":"etc-1b3ngmu","name":"코아클라이밍","region":"etc","area":"경남 김해시","address":"경남 김해시 능동로 159"},
  {"id":"etc-0k9gwmu","name":"퍼스트클라이밍짐","region":"etc","area":"경남 김해시","address":"경남 김해시 가야로 212"},
  {"id":"etc-0tospha","name":"홀드야미클라이밍","region":"etc","area":"경남 김해시","address":"경남 김해시 김해대로 2232"},
  {"id":"etc-05pjlda","name":"볼더서퍼 클라이밍","region":"etc","area":"경남 양산시","address":"경남 양산시 물금읍 황산로 369"},
  {"id":"etc-0j48arm","name":"양클짐","region":"etc","area":"경남 양산시","address":"경남 양산시 북안남3길 11"},
  {"id":"etc-11xkdtm","name":"어썸클라이밍짐","region":"etc","area":"경남 양산시","address":"경남 양산시 물금읍 부산대학로 156"},
  {"id":"etc-1udwkd7","name":"클라임파크","region":"etc","area":"경남 양산시","address":"경남 양산시 상북면 와곡3길 31"},
  {"id":"etc-1m1eh83","name":"빅클라이밍짐","region":"etc","area":"경남 진주시","address":"경남 진주시 정촌면 삼일로105번길 32-15"},
  {"id":"etc-0nu5w26","name":"예티클라이밍짐","region":"etc","area":"경남 진주시","address":"경남 진주시 동진로 415"},
  {"id":"etc-03zgtp3","name":"광클라이밍","region":"etc","area":"경남 창원시","address":"경남 창원시 진해구 장복대로 171"},
  {"id":"etc-1htliky","name":"마산클라이밍스쿨","region":"etc","area":"경남 창원시","address":"경남 창원시 마산회원구 삼호로 63"},
  {"id":"etc-1irab06","name":"비스타 클라이밍짐","region":"etc","area":"경남 창원시","address":"경남 창원시 마산회원구 양덕북17길 41"},
  {"id":"etc-0tjqqt6","name":"창원클라이머스","region":"etc","area":"경남 창원시","address":"경남 창원시 의창구 의안로56번길 46"},
  {"id":"etc-1fngc2v","name":"창원클라이밍스쿨","region":"etc","area":"경남 창원시","address":"경남 창원시 성산구 대원로33번길 18"},
  {"id":"etc-0j1b7ib","name":"크럭스클라이밍","region":"etc","area":"경남 창원시","address":"경남 창원시 마산합포구 월영동서로 11-1"},
  {"id":"etc-1ul2men","name":"클라임존","region":"etc","area":"경남 창원시","address":"경남 창원시 성산구 대암로 161-20"},
  {"id":"etc-1jg7dp9","name":"핫클라이밍짐","region":"etc","area":"경남 창원시","address":"경남 창원시 의창구 사림로137번길 24"},
  {"id":"etc-0hzg9wv","name":"통영락클라이밍","region":"etc","area":"경남 통영시","address":"경남 통영시 도천상가안길 18"},
  {"id":"etc-0inlbb6","name":"구용원","region":"etc","area":"경남 함양군","address":"경남 함양군 함양읍 대실길 274"},
  {"id":"etc-0j3xbqi","name":"오르멍","region":"etc","area":"제주 서귀포시","address":"제주특별자치도 서귀포시 표선면 표선중앙로80번길 1"},
  {"id":"etc-0j6ll56","name":"제주클라이밍스쿨","region":"etc","area":"제주 제주시","address":"제주특별자치도 제주시 서광로 236"},
  {"id":"etc-03464su","name":"픽스볼더 아라점","region":"etc","area":"제주 제주시","address":"제주특별자치도 제주시 중앙로 768"},
  {"id":"etc-1r4ut9z","name":"픽스볼더클라이밍","region":"etc","area":"제주 제주시","address":"제주특별자치도 제주시 삼무로 41"},
];

export const gymsOf = (region: GymRegion) => GYMS.filter((g) => g.region === region);
export const findGym = (id: string) => GYMS.find((g) => g.id === id);
